# Generated by Django 5.2.9 on 2025-12-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used for the URL of the story', unique=True)),
                ('category', models.CharField(choices=[('impact', 'Impact'), ('event', 'Event'), ('community', 'Community'), ('relief', 'Relief'), ('press', 'Press')], default='community', max_length=20)),
                ('summary', models.TextField(help_text='A short teaser for the card view')),
                ('content', models.TextField()),
                ('image_url', models.URLField(help_text='URL to a high-quality photo', max_length=500)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
            ],
            options={
                'verbose_name_plural': 'News Stories',
                'ordering': ['-date_published'],
            },
        ),
    ]
