# Generated by Django 5.2.9 on 2025-12-21 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_corevalue_teammember_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(help_text='SVG path for the category icon')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Program Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('tag', models.CharField(blank=True, help_text='e.g. Weekly, 24/7 Access', max_length=50)),
                ('benefit_metric', models.CharField(blank=True, help_text='e.g. 1,000+ families/week', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='pages.programcategory')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
