# Generated by Django 5.2.9 on 2025-12-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_programcategory_programstat_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('color_hex', models.CharField(default='#0d9488', help_text='Tailwind brand-600 is #0d9488', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('color_choice', models.CharField(choices=[('brand', 'Brand (Teal)'), ('accent', 'Accent (Amber)')], default='brand', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(default='Success Story', max_length=50)),
                ('summary', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Success Stories',
                'ordering': ['order'],
            },
        ),
    ]
