# Generated by Django 5.2.9 on 2025-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactmessage_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('community', 'Community'), ('programs', 'Programs'), ('events', 'Events'), ('facility', 'Our Facility')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-date_added'],
            },
        ),
    ]
