# Generated by Django 5.2.9 on 2025-12-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for the URL of the event', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for the URL of the program', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for the URL of the story', null=True, unique=True),
        ),
    ]
