# Generated by Django 5.2.9 on 2025-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_event_slug_program_slug_successstory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='program',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
