# Generated by Django 6.0.2 on 2026-03-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_newsstory_image_url_remove_program_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='contact@ajhopefoundation.org', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (888) 123-4567', max_length=20)),
                ('zelle_email', models.EmailField(default='ajhopefoundation@gmail.com', max_length=254)),
                ('cashapp_tag', models.CharField(default='$ajhopefoundationgh', max_length=50)),
                ('check_payable_to', models.CharField(default='AJ Hope Foundation', max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='interest',
            field=models.CharField(choices=[('community', 'Community Foundation'), ('education', 'Education & Tutoring'), ('relief', 'Crisis Relief'), ('admin', 'Administrative Support'), ('event', 'Events & Hospitality')], max_length=20),
        ),
    ]
