# Generated by Django 6.0.2 on 2026-03-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_sitesettings_alter_volunteer_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='charity_navigator_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='guidestar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='headquarters_address',
            field=models.TextField(default='123 AJ HOPE Avenue, Faith Plaza, Springfield, IL 62704'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_statement',
            field=models.TextField(default="To demonstrate God's love through practical service, sustainable development, and unwavering community support."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(default='Mon-Fri, 9am - 5pm CST', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_statement',
            field=models.TextField(default='A city where no one is forgotten, and every person has the opportunity to fulfill their potential.'),
        ),
    ]
