# Generated by Django 6.0.2 on 2026-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sitesettings_charity_navigator_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video upload', null=True, upload_to='gallery/videos/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Supporting YouTube, Vimeo, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for images, or as thumbnail for videos', null=True, upload_to='gallery/'),
        ),
    ]
