# Generated by Django 6.0.2 on 2026-03-21 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_galleryimage_video_file_galleryimage_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Check if this is a past/completed program'),
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='events/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.event')),
            ],
            options={
                'verbose_name_plural': 'Event Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='programs/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.program')),
            ],
            options={
                'verbose_name_plural': 'Program Media',
                'ordering': ['order'],
            },
        ),
    ]
