# Generated by Django 6.0.2 on 2026-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_program_completion_date_program_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date the event took place (for past events)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Check if this is a past/completed event'),
        ),
    ]
