# Generated by Django 6.0.2 on 2026-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_regionaloffice_regionalofficephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='help@ajhopefoundation.org', max_length=254),
        ),
    ]
