# Generated by Django 6.0.2 on 2026-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_sitesettings_support_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(blank=True, default='Mon-Fri, 9am - 5pm CST', max_length=100, null=True),
        ),
    ]
