# Generated by Django 6.0.2 on 2026-03-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_sitesettings_office_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. PayPal, Venmo, Zelle', max_length=100)),
                ('value', models.CharField(help_text='The email, tag, or account number', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
