# Generated by Django 6.0.2 on 2026-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_donationmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_mission_image',
            field=models.ImageField(blank=True, help_text='If empty, a default Unsplash image will be used.', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_mission_subtitle',
            field=models.TextField(default='Founded on the principles of unconditional support, AJ HOPE FOUNDATION operates at the intersection of practical relief and spiritual empowerment.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_mission_title',
            field=models.CharField(default='Driven by Compassion, <br><span class="text-accent">Guided by Faith.</span>', help_text='Supports HTML for styling (e.g. &lt;br&gt;, &lt;span&gt;)', max_length=255),
        ),
    ]
