# Generated by Django 6.0.2 on 2026-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_sitesettings_home_mission_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_image',
            field=models.ImageField(blank=True, help_text='Image for the Mission & Vision section on the About page. If empty, a default Unsplash image will be used.', null=True, upload_to='site_settings/'),
        ),
    ]
