# Generated by Django 6.0.2 on 2026-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_sitesettings_about_mission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_title',
            field=models.CharField(default='Driven by a vision of a restored and flourishing community.', help_text='Headline for the Mission & Vision section on the About page. Supports HTML.', max_length=255),
        ),
    ]
